name: Flutter CI

on:
  push:
    tags:
      - 'v*.*'

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v1
      with:
        channel: 'stable'

    - name: Install dependencies
      run: flutter pub get

    - name: Upgrade dependencies
      run: flutter pub upgrade

    - name: Build APK
      run: flutter build apk --release --target-platform=android-arm64

    - name: Upload APK artifact
      uses: actions/upload-artifact@v2
      with:
        name: app-release.apk
        path: build/app/outputs/flutter-apk/app-release.apk

  build-ios:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v1
      with:
        channel: 'stable'

    - name: Install dependencies
      run: flutter pub get

    - name: Upgrade dependencies
      run: flutter pub upgrade

    - name: Build iOS
      run: flutter build ios --release --no-codesign

    - name: Prepare IPA
      run: |
        mkdir -p Payload
        mv build/ios/iphoneos/Runner.app Payload/
        zip -r Runner.zip Payload
        mv Runner.zip Runner.ipa

    - name: Upload IPA artifact
      uses: actions/upload-artifact@v2
      with:
        name: Runner.ipa
        path: Runner.ipa

  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v1
      with:
        channel: 'stable'

    - name: Install dependencies
      run: flutter pub get

    - name: Upgrade dependencies
      run: flutter pub upgrade

    - name: Build Windows
      run: flutter build windows --release

    - name: Prepare Windows artifact
      run: |
        Compress-Archive -Path build/windows/runner/Release/* -DestinationPath app-release.zip

    - name: Upload Windows artifact
      uses: actions/upload-artifact@v2
      with:
        name: app-release.zip
        path: app-release.zip

  create-release:
    runs-on: ubuntu-latest
    needs: [build-android, build-ios, build-windows]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download APK artifact
      uses: actions/download-artifact@v2
      with:
        name: app-release.apk
        path: ./

    - name: Download IPA artifact
      uses: actions/download-artifact@v2
      with:
        name: Runner.ipa
        path: ./

    - name: Download Windows artifact
      uses: actions/download-artifact@v2
      with:
        name: app-release.zip
        path: ./

    - name: Create Release
      id: create_release
      uses: ncipollo/release-action@v1.8.10
      with:
        artifacts: |
          app-release.apk
          Runner.ipa
          app-release.zip
        token: ${{ secrets.TOKEN }}
        tag: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false